# Generated by Django 4.2.7 on 2023-11-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('maritalStatus', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
            ],
        ),
    ]
