# Generated by Django 4.2.7 on 2023-11-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='fingerprint_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='fingerprint_education',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='fingerprint_maritalStatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='fingerprint_name',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='fingerprint_occupation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='fingerprint_race',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='fingerprint_sex',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
