# Generated by Django 4.2.7 on 2023-11-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0002_user_details_fingerprint_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='fingerprint_age',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='fingerprint_education',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='fingerprint_maritalStatus',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='fingerprint_name',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='fingerprint_occupation',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='fingerprint_race',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='fingerprint_sex',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
