# Generated by Django 4.2.3 on 2023-11-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0003_alter_user_details_fingerprint_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='fingerprint_education',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='fingerprint_maritalStatus',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='fingerprint_occupation',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='fingerprint_race',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='fingerprint_sex',
        ),
    ]
