# Generated by Django 4.2.3 on 2023-11-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0004_remove_user_details_fingerprint_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='fingerprint_education',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='fingerprint_maritalStatus',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='fingerprint_occupation',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='fingerprint_race',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='fingerprint_sex',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
